export const ACTION_USER_OPEN_SEARCH = 'ACTION_USER_OPEN_SEARCH';
export const ACTION_USER_CLOSE_SEARCH = 'ACTION_USER_CLOSE_SEARCH';
export const ACTION_USER_OPEN_PROFILE = 'ACTION_USER_OPEN_PROFILE';
export const ACTION_USER_CLOSE_PROFILE = 'ACTION_USER_CLOSE_PROFILE';
