export const ACTION_USER_OPEN_SEARCH = 'ACTION_USER_OPEN_SEARCH';
export const ACTION_USER_CLOSE_SEARCH = 'ACTION_USER_CLOSE_SEARCH';
export const ACTION_USER_OPEN_PROFILE = 'ACTION_USER_OPEN_PROFILE';
export const ACTION_USER_CLOSE_PROFILE = 'ACTION_USER_CLOSE_PROFILE';
export const ACTION_USER_LOGIN = 'ACTION_USER_LOGIN';
export const ACTION_USER_LOGOUT = 'ACTION_USER_LOGOUT';
export const ACTION_USER_OPEN_NOTIFICATIONS = 'ACTION_USER_OPEN_NOTIFICATIONS';
export const ACTION_USER_CLOSE_NOTIFICATIONS = 'ACTION_USER_CLOSE_NOTIFICATIONS';
export const ACTION_USER_OPEN_REQUESTS = 'ACTION_USER_OPEN_REQUESTS';
export const ACTION_USER_CLOSE_REQUESTS = 'ACTION_USER_CLOSE_REQUESTS';

export const ACTION_POST_GET_ALL = 'ACTION_POST_GET_ALL';
export const ACTION_POST_GET_FAIL = 'ACTION_POST_GET_FAIL';
